services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - APP_URL=localhost
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres?schema=public
      - SESSION_SECRET=sessionSecret
      - HCAPTCHA_SITEKEY=10000000-ffff-ffff-ffff-000000000001
      - HCAPTCHA_SECRET=0x
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
